/***************************************************************************
 * The contents of this file were generated with Amplify Studio.           *
 * Please refrain from making any modifications to this file.              *
 * Any changes to this file will be overwritten when running amplify pull. *
 **************************************************************************/

import * as React from "react";
import { EscapeHatchProps } from "@aws-amplify/ui-react/internal";
import { FlexProps, IconProps, TextProps, ViewProps } from "@aws-amplify/ui-react";
export declare type PrimitiveOverrideProps<T> = Partial<T> & React.DOMAttributes<HTMLDivElement>;
export declare type Desktop2OverridesProps = {
    Desktop2?: PrimitiveOverrideProps<ViewProps>;
    Zone1?: PrimitiveOverrideProps<ViewProps>;
    "Frame 2"?: PrimitiveOverrideProps<FlexProps>;
    "\u65E5\u7A0B\u4E00\u89A7"?: PrimitiveOverrideProps<TextProps>;
    "Frame 1"?: PrimitiveOverrideProps<FlexProps>;
    "\u30B9\u30BF\u30C3\u30D5No."?: PrimitiveOverrideProps<TextProps>;
    "\u30B9\u30BF\u30C3\u30D5\u6C0F\u540D"?: PrimitiveOverrideProps<TextProps>;
    "Rectangle 1"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 2"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 310114"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 5"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 4"?: PrimitiveOverrideProps<ViewProps>;
    "Frame 8"?: PrimitiveOverrideProps<FlexProps>;
    "material-symbols:add"?: PrimitiveOverrideProps<ViewProps>;
    Vector?: PrimitiveOverrideProps<IconProps>;
    "\u5E0C\u671B\u65E5\u8FFD\u52A0"?: PrimitiveOverrideProps<TextProps>;
    "Frame 6"?: PrimitiveOverrideProps<FlexProps>;
    "\u7DE8\u96C6"?: PrimitiveOverrideProps<TextProps>;
    "Rectangle 310117"?: PrimitiveOverrideProps<ViewProps>;
    "Frame 7"?: PrimitiveOverrideProps<FlexProps>;
    "\u524A\u9664"?: PrimitiveOverrideProps<TextProps>;
    "Frame 5"?: PrimitiveOverrideProps<FlexProps>;
    "\u30ED\u30B0\u30A2\u30A6\u30C8"?: PrimitiveOverrideProps<TextProps>;
    "Rectangle 8"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 9"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 10"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 11"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 12"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 13"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 14"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 15"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 16"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 17"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 18"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 19"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 20"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 21"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 22"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 23"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 24"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 25"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 26"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 27"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 28"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 29"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 30"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 31"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 32"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 33"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 34"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 35"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 36"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 37"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 38"?: PrimitiveOverrideProps<ViewProps>;
    "Frame 12"?: PrimitiveOverrideProps<FlexProps>;
    "\u5E0C\u671B\u65E51796"?: PrimitiveOverrideProps<TextProps>;
    "Rectangle 39"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 40"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 41"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 42"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 43"?: PrimitiveOverrideProps<ViewProps>;
    "Frame 11"?: PrimitiveOverrideProps<FlexProps>;
    "\u5E0C\u671B\u65E51793"?: PrimitiveOverrideProps<TextProps>;
    "Frame 131797"?: PrimitiveOverrideProps<FlexProps>;
    "\u7B2C1\u5E0C\u671B"?: PrimitiveOverrideProps<TextProps>;
    "Frame 141799"?: PrimitiveOverrideProps<FlexProps>;
    "\u7B2C5\u5E0C\u671B"?: PrimitiveOverrideProps<TextProps>;
    "Frame 1317101"?: PrimitiveOverrideProps<FlexProps>;
    "\u7B2C4\u5E0C\u671B"?: PrimitiveOverrideProps<TextProps>;
    "Frame 1417103"?: PrimitiveOverrideProps<FlexProps>;
    "\u7B2C3\u5E0C\u671B"?: PrimitiveOverrideProps<TextProps>;
    "Frame 15"?: PrimitiveOverrideProps<FlexProps>;
    "\u7B2C2\u5E0C\u671B"?: PrimitiveOverrideProps<TextProps>;
    "Frame 16"?: PrimitiveOverrideProps<FlexProps>;
    "\u65E5\u4ED8"?: PrimitiveOverrideProps<TextProps>;
    "Frame 17"?: PrimitiveOverrideProps<FlexProps>;
    "\u6642\u9593"?: PrimitiveOverrideProps<TextProps>;
    "Frame 18"?: PrimitiveOverrideProps<FlexProps>;
    "\u5834\u6240"?: PrimitiveOverrideProps<TextProps>;
    "Frame 19"?: PrimitiveOverrideProps<FlexProps>;
    "\u30AA\u30D7\u30B7\u30E7\u30F3"?: PrimitiveOverrideProps<TextProps>;
    "Frame 20"?: PrimitiveOverrideProps<FlexProps>;
    "\u6C7A\u5B9A"?: PrimitiveOverrideProps<TextProps>;
} & EscapeHatchProps;
export declare type Desktop2Props = React.PropsWithChildren<Partial<ViewProps> & {
    overrides?: Desktop2OverridesProps | undefined | null;
}>;
export default function Desktop2(props: Desktop2Props): React.ReactElement;
